apiVersion: v1
kind: Secret
metadata:
  name: dockercreds
  annotations:
          tekton.dev/docker-0: https://index.docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: chocopath
  password: F/WBU/Mx_;~4Kp3