
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evsahara
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: evsahara
    repoURL: https://github.com/ChocoPath/evsahara
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}